# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aaron Agarunov
email: agarunov.aaron@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aaron Agarunov's portfolio & personal site. Get in touch at agarunovaaron at gmail dot com.
baseurl: "" # the subpath of your site, e.g. /blog
repository: agarun/agarun.github.io
url: "https://agarun.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: agarune
github_username:  agarun

# Build settings
markdown: kramdown

google_analytics: UA-107334049-1

# permalink: /:title/

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
